# Generated by Django 4.2 on 2023-04-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_author_category_remove_book_author_book_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/author'),
        ),
        migrations.AddField(
            model_name='author',
            name='resume',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='media/book'),
        ),
    ]
